// Types
export type {
  UserRole,
  Gender,
  ActivityLevel,
  FitnessGoal,
  MealType,
  BodyPart,
  Equipment,
  ClientStatus,
  SubscriptionStatus,
  AIUsageType,
  TrainingExperience,
  EquipmentAccess,
  TrainingStyle,
  CookingSkill,
  MealPrepPreference,
  WorkType,
  SleepQuality,
  StressLevel,
  GoalTimeline,
  SupplementFrequency,
  SupplementTime,
  UserProfile,
  NutritionistPackage,
  NutritionistClient,
  AIUsage,
  FoodItem,
  DietPlan,
  DietPlanMeal,
  MealLog,
  Exercise,
  TrainingPlan,
  TrainingPlanDay,
  TrainingPlanExercise,
  WorkoutSetLog,
  WorkoutExerciseLog,
  WorkoutLog,
  CardioType,
  CardioSession,
  WaterLog,
  WeightLog,
  Subscription,
  UserSupplement,
  SupplementLog,
  FeedbackStatus,
  Conversation,
  Message,
  FeedbackQuestion,
  FeedbackResponse,
  FeedbackRequest,
  TierSelectionType,
  UserTierSelection,
} from './types'

// Nutrition
export type { UserMetrics, NutritionTargets } from './nutrition'
export {
  calculateBMR,
  calculateTDEE,
  adjustCaloriesForGoal,
  calculateMacros,
  calculateWaterIntake,
  calculateNutritionTargets,
  getActivityLevelName,
  getGoalName,
} from './nutrition'

// Training
export { parseRepRange, calculateSuggestion } from './training'

// Cardio
export { calculateCardioCalories } from './cardio'

// Constants
export {
  PRICING,
  BODY_PARTS,
  EQUIPMENT_TYPES,
  CARDIO_TYPES,
  ACTIVITY_LEVELS,
  FITNESS_GOALS,
  MEAL_TYPES,
  WEIGHT_INCREMENT_COMPOUND,
  WEIGHT_INCREMENT_ISOLATION,
  DEFAULT_REST_SECONDS,
  DEFAULT_SETS,
  DEFAULT_REPS,
  WATER_QUICK_ADD,
  // Anamnesis
  TRAINING_EXPERIENCE,
  EQUIPMENT_ACCESS,
  TRAINING_STYLES,
  COMMON_INJURIES,
  COMMON_CONDITIONS,
  DIETARY_RESTRICTIONS,
  COMMON_FOOD_DISLIKES,
  COOKING_SKILLS,
  MEAL_PREP_PREFERENCES,
  WORK_TYPES,
  SLEEP_QUALITY_OPTIONS,
  STRESS_LEVELS,
  GOAL_TIMELINES,
  MOTIVATIONS,
  SUPPLEMENT_FREQUENCIES,
  SUPPLEMENT_TIMES,
  COMMON_SUPPLEMENTS,
} from './constants'
export type { PlanType } from './constants'
