export const COMPANY_NAME = 'Treno'
export const BRAND_NAME = 'Treno'
export const SUPPORT_EMAIL = 'support@treno.app'
export const LEGAL_JURISDICTION = 'England and Wales'
export const LAST_POLICY_UPDATE = '4 April 2026'
