export const COMPANY_NAME = 'Meal & Motion'
export const BRAND_NAME = 'Meal & Motion'
export const SUPPORT_EMAIL = 'support@mealandmotion.app'
export const LEGAL_JURISDICTION = 'England and Wales'
export const LAST_POLICY_UPDATE = '4 April 2026'
